name: Build and Release LaTeX PDF

on:
  push:
    tags:
      - 'v*'
    paths:
      - '**.tex'
      - '**.png'
      - '**.jpg'
  workflow_dispatch:

jobs:
  detect-chapters:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find all chapter*.tex files
        id: set-matrix
        run: |
          files=$(find . -name 'chapter*.tex' | sed 's|^\./||')
          matrix=$(printf '%s\n' "$files" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    needs: detect-chapters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.detect-chapters.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.file }}
          compiler: xelatex
          extra_system_packages: fonts-noto-cjk

      - name: Rename PDF
        run: |
          base=$(basename "${{ matrix.file }}" .tex)
          mv "$base-${{ github.ref_name }}.pdf" "${base}.pdf"
          echo "artifact name: $base-pdf"
          mkdir -p out && mv "${base}.pdf" out/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chapter-${{ matrix.file }}
          path: out/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: chapter-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: chapter*-*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
