name: Build All LaTeX Chapters

on:
  push:
    paths:
      - '**.tex'
      - '**.png'
      - '**.jpg'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install fonts
        run: |
          sudo apt update
          sudo apt install -y fonts-noto-cjk
          mkdir -p .fonts
          cp /usr/share/fonts/opentype/noto/*.ttc .fonts/

      - name: Compile all chapters
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            chapter0.tex
          latexmk_use_xelatex: true
          extra_fonts: .fonts

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-chapters
          path: |
            chapter0.pdf