name: Build All LaTeX Chapters

on:
  push:
    paths:
      - '**.tex'
      - '**.png'
      - '**.jpg'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TeX Live + Fonts
        run: |
          sudo apt update
          sudo apt install -y \
            texlive-full \
            fonts-noto-cjk \
            latexmk

      - name: Compile all chapters
        run: |
          latexmk -pdf -xelatex -interaction=nonstopmode -halt-on-error chapter0.tex

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-chapters
          path: chapter0.pdf